---
application_name: Claryence
business_name: Claryence Limited
business_address: 
domain: claryence.com
support_email: support@claryence.com
default_from_email: Claryence <tom@tomeehan.net>
background_job_processor: sidekiq
email_provider: postmark
account_types: both
apns: false
fcm: false
integrations:
omniauth_providers:
payment_processors:
multitenancy:
gems:
